// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qblthvvbwxufnhzjhihc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFibHRodnZid3h1Zm5oempoaWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDY4MDMsImV4cCI6MjA2NTIyMjgwM30.Lr9pcERHSiPbWXQJa2cb3VqGYq1q6gXhYRB4kXe1gPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);